apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - image: gcr.io/mno-b2b-bss-dev/backend:313ede3_20230223191015
          name: backend
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: database
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.0.0
          args:
            - "--structured-logs"
            - "--port=3306"
            - "mno-b2b-bss-dev:asia-northeast1:spm-mysql"
          securityContext:
            runAsNonRoot: true
          volumeMounts:
            - name: db-sa-volume
              mountPath: /secrets/
              readOnly: true
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
      volumes:
        - name: db-sa-volume
          secret:
            secretName: db-sa
